name: P12Changer
options:
  bundleIdPrefix: com.malupiton
targets:
  P12Changer:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.malupiton.p12changer
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      # Matikan code signing agar bisa jadi IPA bersih untuk TrollStore / 3uTools
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
      ENABLE_BITCODE: "NO"
