name: P12Changer
options:
  bundleIdPrefix: com.ibaalpremium
targets:
  P12Changer:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ibaalpremium.p12changer
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      
      # Generate Info.plist otomatis
      GENERATE_INFOPLIST_FILE: "YES"
      
      # Matikan Code Signing & Entitlements secara brutal untuk Xcode 16
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
      ENTITLEMENTS_REQUIRED: "NO"
